dependencies:
  - name: mariadb
    version: 7.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
    tags:
      - wordpress-database
  - name: nginx-ingress
  version: 1.41.2
  repository: https://kubernetes-charts.storage.googleapis.com  
